plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/anmolvarma/personal/portfolio/build"
publishOrigin = "ui"
command = "yarn build"
commandOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]